# Generated by Django 6.1.1 on 2026-09-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workplace",
            options={
                "permissions": [
                    ("move_workplace", "Может перемещать сотрудников между столами")
                ]
            },
        ),
    ]
