# Generated by Django 6.1.1 on 2026-09-26 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tester", "Тестировщик"),
                    ("frontend", "Фронтендер"),
                    ("backend", "Бекендер"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="EmployeeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="employees/")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
