# Generated by Django 6.1.1 on 2026-09-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employee_hire_date_employee_role_employeeimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "permissions": [
                    ("move_employee", "Может перемещать сотрудников между столами"),
                    ("manage_employees", "Может управлять сотрудниками (CRUD)"),
                ],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
